BEGIN;

DROP SCHEMA IF EXISTS retrosheet CASCADE;
CREATE SCHEMA retrosheet;

CREATE TABLE retrosheet.events (
    "game_id" VARCHAR(12) NOT NULL,
    "away_team_id" VARCHAR(3) NOT NULL,
    "inn_ct" INTEGER NOT NULL,
    "bat_home_id" INTEGER NOT NULL,
    "outs_ct" INTEGER NOT NULL,
    "balls_ct" INTEGER NOT NULL,
    "strikes_ct" INTEGER NOT NULL,
    "pitch_seq_tx" TEXT NOT NULL,
    "away_score_ct" INTEGER NOT NULL,
    "home_score_ct" INTEGER NOT NULL,
    "bat_id" VARCHAR(8) NOT NULL,
    "bat_hand_cd" VARCHAR(1) NOT NULL,
    "resp_bat_id" VARCHAR(8) NOT NULL,
    "resp_bat_hand_cd" VARCHAR(1) NOT NULL,
    "pit_id" VARCHAR(8) NOT NULL,
    "pit_hand_cd" VARCHAR(1) NOT NULL,
    "resp_pit_id" VARCHAR(8) NOT NULL,
    "resp_pit_hand_cd" VARCHAR(1) NOT NULL,
    "pos2_fld_id" VARCHAR(8) NOT NULL,
    "pos3_fld_id" VARCHAR(8) NOT NULL,
    "pos4_fld_id" VARCHAR(8) NOT NULL,
    "pos5_fld_id" VARCHAR(8) NOT NULL,
    "pos6_fld_id" VARCHAR(8) NOT NULL,
    "pos7_fld_id" VARCHAR(8) NOT NULL,
    "pos8_fld_id" VARCHAR(8) NOT NULL,
    "pos9_fld_id" VARCHAR(8) NOT NULL,
    "base1_run_id" VARCHAR(8),
    "base2_run_id" VARCHAR(8),
    "base3_run_id" VARCHAR(8),
    "event_tx" TEXT NOT NULL,
    "leadoff_fl" BOOLEAN NOT NULL,
    "ph_fl" BOOLEAN NOT NULL,
    "bat_fld_cd" INTEGER NOT NULL,
    "bat_lineup_id" INTEGER NOT NULL,
    "event_cd" INTEGER NOT NULL,
    "bat_event_fl" BOOLEAN NOT NULL,
    "ab_fl" BOOLEAN NOT NULL,
    "h_fl" INTEGER NOT NULL,
    "sh_fl" BOOLEAN NOT NULL,
    "sf_fl" BOOLEAN NOT NULL,
    "event_outs_ct" INTEGER NOT NULL,
    "dp_fl" BOOLEAN NOT NULL,
    "tp_fl" BOOLEAN NOT NULL,
    "rbi_ct" INTEGER NOT NULL,
    "wp_fl" BOOLEAN NOT NULL,
    "pb_fl" BOOLEAN NOT NULL,
    "fld_cd" INTEGER NOT NULL,
    "battedball_cd" VARCHAR(1) NOT NULL,
    "bunt_fl" BOOLEAN NOT NULL,
    "foul_fl" BOOLEAN NOT NULL,
    "battedball_loc_tx" TEXT,
    "err_ct" INTEGER NOT NULL,
    "err1_fld_cd" INTEGER NOT NULL,
    "err1_cd" VARCHAR(1) NOT NULL,
    "err2_fld_cd" INTEGER NOT NULL,
    "err2_cd" VARCHAR(1) NOT NULL,
    "err3_fld_cd" INTEGER NOT NULL,
    "err3_cd" VARCHAR(1) NOT NULL,
    "bat_dest_id" INTEGER NOT NULL,
    "run1_dest_id" INTEGER NOT NULL,
    "run2_dest_id" INTEGER NOT NULL,
    "run3_dest_id" INTEGER NOT NULL,
    "bat_play_tx" TEXT,
    "run1_play_tx" TEXT,
    "run2_play_tx" TEXT,
    "run3_play_tx" TEXT,
    "run1_sb_fl" BOOLEAN NOT NULL,
    "run2_sb_fl" BOOLEAN NOT NULL,
    "run3_sb_fl" BOOLEAN NOT NULL,
    "run1_cs_fl" BOOLEAN NOT NULL,
    "run2_cs_fl" BOOLEAN NOT NULL,
    "run3_cs_fl" BOOLEAN NOT NULL,
    "run1_pk_fl" BOOLEAN NOT NULL,
    "run2_pk_fl" BOOLEAN NOT NULL,
    "run3_pk_fl" BOOLEAN NOT NULL,
    "run1_resp_pit_id" VARCHAR(8),
    "run2_resp_pit_id" VARCHAR(8),
    "run3_resp_pit_id" VARCHAR(8),
    "game_new_fl" BOOLEAN NOT NULL,
    "game_end_fl" BOOLEAN NOT NULL,
    "pr_run1_fl" BOOLEAN NOT NULL,
    "pr_run2_fl" BOOLEAN NOT NULL,
    "pr_run3_fl" BOOLEAN NOT NULL,
    "removed_for_pr_run1_id" VARCHAR(8),
    "removed_for_pr_run2_id" VARCHAR(8),
    "removed_for_pr_run3_id" VARCHAR(8),
    "removed_for_ph_bat_id" VARCHAR(8),
    "removed_for_ph_bat_fld_cd" INTEGER NOT NULL,
    "po1_fld_cd" INTEGER NOT NULL,
    "po2_fld_cd" INTEGER NOT NULL,
    "po3_fld_cd" INTEGER NOT NULL,
    "ass1_fld_cd" INTEGER NOT NULL,
    "ass2_fld_cd" INTEGER NOT NULL,
    "ass3_fld_cd" INTEGER NOT NULL,
    "ass4_fld_cd" INTEGER NOT NULL,
    "ass5_fld_cd" INTEGER NOT NULL,
    "event_id" INTEGER NOT NULL
);

CREATE TABLE retrosheet.games (
    "game_id" VARCHAR(12) NOT NULL,
    "game_dt" DATE NOT NULL,
    "game_ct" INTEGER NOT NULL,
    "game_dy" VARCHAR(9) NOT NULL,
    "start_game_tm" INTEGER NOT NULL,
    "dh_fl" BOOLEAN NOT NULL,
    "daynight_park_cd" VARCHAR(1) NOT NULL,
    "away_team_id" VARCHAR(3) NOT NULL,
    "home_team_id" VARCHAR(3) NOT NULL,
    "park_id" VARCHAR(5) NOT NULL,
    "away_start_pit_id" VARCHAR(8) NOT NULL,
    "home_start_pit_id" VARCHAR(8) NOT NULL,
    "base4_ump_id" VARCHAR(8),
    "base1_ump_id" VARCHAR(8),
    "base2_ump_id" VARCHAR(8),
    "base3_ump_id" VARCHAR(8),
    "lf_ump_id" VARCHAR(8),
    "rf_ump_id" VARCHAR(8),
    "attend_park_ct" INTEGER,
    "scorer_record_id" TEXT,
    "translator_record_id" TEXT,
    "inputter_record_id" TEXT,
    "input_record_ts" TEXT,
    "edit_record_ts" TEXT,
    "method_record_cd" INTEGER NOT NULL,
    "pitches_record_cd" INTEGER NOT NULL,
    "temp_park_ct" INTEGER NOT NULL,
    "wind_direction_park_cd" INTEGER NOT NULL,
    "wind_speed_park_ct" INTEGER NOT NULL,
    "field_park_cd" INTEGER NOT NULL,
    "precip_park_cd" INTEGER NOT NULL,
    "sky_park_cd" INTEGER NOT NULL,
    "minutes_game_ct" INTEGER NOT NULL,
    "inn_ct" INTEGER NOT NULL,
    "away_score_ct" INTEGER NOT NULL,
    "home_score_ct" INTEGER NOT NULL,
    "away_hits_ct" INTEGER NOT NULL,
    "home_hits_ct" INTEGER NOT NULL,
    "away_err_ct" INTEGER NOT NULL,
    "home_err_ct" INTEGER NOT NULL,
    "away_lob_ct" INTEGER NOT NULL,
    "home_lob_ct" INTEGER NOT NULL,
    "win_pit_id" VARCHAR(8) NOT NULL,
    "lose_pit_id" VARCHAR(8) NOT NULL,
    "save_pit_id" VARCHAR(8),
    "gwrbi_bat_id" VARCHAR(8),
    "away_lineup1_bat_id" VARCHAR(8) NOT NULL,
    "away_lineup1_fld_cd" INTEGER NOT NULL,
    "away_lineup2_bat_id" VARCHAR(8) NOT NULL,
    "away_lineup2_fld_cd" INTEGER NOT NULL,
    "away_lineup3_bat_id" VARCHAR(8) NOT NULL,
    "away_lineup3_fld_cd" INTEGER NOT NULL,
    "away_lineup4_bat_id" VARCHAR(8) NOT NULL,
    "away_lineup4_fld_cd" INTEGER NOT NULL,
    "away_lineup5_bat_id" VARCHAR(8) NOT NULL,
    "away_lineup5_fld_cd" INTEGER NOT NULL,
    "away_lineup6_bat_id" VARCHAR(8) NOT NULL,
    "away_lineup6_fld_cd" INTEGER NOT NULL,
    "away_lineup7_bat_id" VARCHAR(8) NOT NULL,
    "away_lineup7_fld_cd" INTEGER NOT NULL,
    "away_lineup8_bat_id" VARCHAR(8) NOT NULL,
    "away_lineup8_fld_cd" INTEGER NOT NULL,
    "away_lineup9_bat_id" VARCHAR(8) NOT NULL,
    "away_lineup9_fld_cd" INTEGER NOT NULL,
    "home_lineup1_bat_id" VARCHAR(8) NOT NULL,
    "home_lineup1_fld_cd" INTEGER NOT NULL,
    "home_lineup2_bat_id" VARCHAR(8) NOT NULL,
    "home_lineup2_fld_cd" INTEGER NOT NULL,
    "home_lineup3_bat_id" VARCHAR(8) NOT NULL,
    "home_lineup3_fld_cd" INTEGER NOT NULL,
    "home_lineup4_bat_id" VARCHAR(8) NOT NULL,
    "home_lineup4_fld_cd" INTEGER NOT NULL,
    "home_lineup5_bat_id" VARCHAR(8) NOT NULL,
    "home_lineup5_fld_cd" INTEGER NOT NULL,
    "home_lineup6_bat_id" VARCHAR(8) NOT NULL,
    "home_lineup6_fld_cd" INTEGER NOT NULL,
    "home_lineup7_bat_id" VARCHAR(8) NOT NULL,
    "home_lineup7_fld_cd" INTEGER NOT NULL,
    "home_lineup8_bat_id" VARCHAR(8) NOT NULL,
    "home_lineup8_fld_cd" INTEGER NOT NULL,
    "home_lineup9_bat_id" VARCHAR(8) NOT NULL,
    "home_lineup9_fld_cd" INTEGER NOT NULL,
    "away_finish_pit_id" VARCHAR(8),
    "home_finish_pit_id" VARCHAR(8)
);

COMMIT;
